/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50:  '#f0f4ff',
          100: '#e0e9ff',
          200: '#c7d6ff',
          300: '#a4b8ff',
          400: '#7b91ff',
          500: '#5B6EF5',
          600: '#4654e0',
          700: '#3840c7',
          800: '#2e35a0',
          900: '#29307f',
          950: '#1a1f4e',
        },
        surface: {
          50:  '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          900: '#0a0d14',
          800: '#141820',
          700: '#1a1f2e',
          600: '#1e2535',
          500: '#252d3d',
          400: '#4a5568',
        },
        accent: {
          purple: '#8B5CF6',
          pink:   '#EC4899',
          cyan:   '#06B6D4',
          green:  '#10B981',
          orange: '#F59E0B',
          red:    '#EF4444',
        },
        // Theme-aware via CSS variables
        theme: {
          bg:        'var(--color-bg)',
          surface:   'var(--color-surface)',
          elevated:  'var(--color-surface-elevated)',
          overlay:   'var(--color-surface-overlay)',
          input:     'var(--color-input)',
          border:    'var(--color-border)',
          primary:   'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted:     'var(--color-text-muted)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      borderRadius: {
        '4xl': '2rem',
      },
      spacing: {
        'navbar': 'var(--navbar-height)',
        'sidebar': 'var(--sidebar-width)',
      },
      maxWidth: {
        'content': 'var(--max-content)',
      },
      boxShadow: {
        'glass':  'var(--glass-shadow)',
        'brand':  'var(--shadow-brand)',
        'card':   'var(--shadow-card)',
        'input':  'var(--shadow-input)',
        'float':  'var(--shadow-float)',
        'theme-xs': 'var(--shadow-xs)',
        'theme-sm': 'var(--shadow-sm)',
        'theme-md': 'var(--shadow-md)',
        'theme-lg': 'var(--shadow-lg)',
        'theme-xl': 'var(--shadow-xl)',
      },
      animation: {
        'fade-in':      'fadeIn 0.3s ease-out',
        'slide-up':     'slideUp 0.4s cubic-bezier(0.16,1,0.3,1)',
        'slide-down':   'slideDown 0.4s cubic-bezier(0.16,1,0.3,1)',
        'slide-right':  'slideInRight 0.3s cubic-bezier(0.16,1,0.3,1)',
        'slide-left':   'slideInLeft 0.3s cubic-bezier(0.16,1,0.3,1)',
        'scale-in':     'scaleIn 0.2s ease-out',
        'shimmer':      'shimmer 2s linear infinite',
        'glow':         'glow 2s ease-in-out infinite alternate',
        'float':        'float 3s ease-in-out infinite',
        'pulse-glow':   'pulse-glow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:       { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp:      { '0%': { transform: 'translateY(16px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideDown:    { '0%': { transform: 'translateY(-16px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideInRight: { '0%': { transform: 'translateX(100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        slideInLeft:  { '0%': { transform: 'translateX(-100%)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        scaleIn:      { '0%': { transform: 'scale(0.95)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        shimmer:      { '0%': { backgroundPosition: '-1000px 0' }, '100%': { backgroundPosition: '1000px 0' } },
        glow:         { '0%': { boxShadow: '0 0 20px var(--color-brand-glow)' }, '100%': { boxShadow: '0 0 40px var(--color-brand-glow)' } },
        float:        { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};